
package com.webservice.webserviceexample;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "paqueteImplService", targetNamespace = "http://webserviceexample.webservice.com/", wsdlLocation = "http://localhost:8068/webserviceexample/paquete?wsdl")
public class PaqueteImplService
    extends Service
{

    private final static URL PAQUETEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAQUETEIMPLSERVICE_EXCEPTION;
    private final static QName PAQUETEIMPLSERVICE_QNAME = new QName("http://webserviceexample.webservice.com/", "paqueteImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8068/webserviceexample/paquete?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAQUETEIMPLSERVICE_WSDL_LOCATION = url;
        PAQUETEIMPLSERVICE_EXCEPTION = e;
    }

    public PaqueteImplService() {
        super(__getWsdlLocation(), PAQUETEIMPLSERVICE_QNAME);
    }

    public PaqueteImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAQUETEIMPLSERVICE_QNAME, features);
    }

    public PaqueteImplService(URL wsdlLocation) {
        super(wsdlLocation, PAQUETEIMPLSERVICE_QNAME);
    }

    public PaqueteImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAQUETEIMPLSERVICE_QNAME, features);
    }

    public PaqueteImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaqueteImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Paquete
     */
    @WebEndpoint(name = "paqueteImplPort")
    public Paquete getPaqueteImplPort() {
        return super.getPort(new QName("http://webserviceexample.webservice.com/", "paqueteImplPort"), Paquete.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Paquete
     */
    @WebEndpoint(name = "paqueteImplPort")
    public Paquete getPaqueteImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webserviceexample.webservice.com/", "paqueteImplPort"), Paquete.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAQUETEIMPLSERVICE_EXCEPTION!= null) {
            throw PAQUETEIMPLSERVICE_EXCEPTION;
        }
        return PAQUETEIMPLSERVICE_WSDL_LOCATION;
    }

}
